/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as CategorySlugRouteImport } from './routes/category.$slug'
import { Route as ArticleSlugRouteImport } from './routes/article.$slug'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as NewsJilaSlugIndexRouteImport } from './routes/news.$jilaSlug.index'
import { Route as NewsJilaSlugCategoryCategorySlugRouteImport } from './routes/news.$jilaSlug.category.$categorySlug'
import { Route as NewsJilaSlugDistrictSubDistrictSlugIndexRouteImport } from './routes/news.$jilaSlug.district.$subDistrictSlug.index'
import { Route as NewsJilaSlugDistrictSubDistrictSlugCategoryCategorySlugRouteImport } from './routes/news.$jilaSlug.district.$subDistrictSlug.category.$categorySlug'

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticleSlugRoute = ArticleSlugRouteImport.update({
  id: '/article/$slug',
  path: '/article/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const NewsJilaSlugIndexRoute = NewsJilaSlugIndexRouteImport.update({
  id: '/news/$jilaSlug/',
  path: '/news/$jilaSlug/',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsJilaSlugCategoryCategorySlugRoute =
  NewsJilaSlugCategoryCategorySlugRouteImport.update({
    id: '/news/$jilaSlug/category/$categorySlug',
    path: '/news/$jilaSlug/category/$categorySlug',
    getParentRoute: () => rootRouteImport,
  } as any)
const NewsJilaSlugDistrictSubDistrictSlugIndexRoute =
  NewsJilaSlugDistrictSubDistrictSlugIndexRouteImport.update({
    id: '/news/$jilaSlug/district/$subDistrictSlug/',
    path: '/news/$jilaSlug/district/$subDistrictSlug/',
    getParentRoute: () => rootRouteImport,
  } as any)
const NewsJilaSlugDistrictSubDistrictSlugCategoryCategorySlugRoute =
  NewsJilaSlugDistrictSubDistrictSlugCategoryCategorySlugRouteImport.update({
    id: '/news/$jilaSlug/district/$subDistrictSlug/category/$categorySlug',
    path: '/news/$jilaSlug/district/$subDistrictSlug/category/$categorySlug',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/users': typeof AdminUsersRoute
  '/article/$slug': typeof ArticleSlugRoute
  '/category/$slug': typeof CategorySlugRoute
  '/admin/': typeof AdminIndexRoute
  '/news/$jilaSlug/': typeof NewsJilaSlugIndexRoute
  '/news/$jilaSlug/category/$categorySlug': typeof NewsJilaSlugCategoryCategorySlugRoute
  '/news/$jilaSlug/district/$subDistrictSlug/': typeof NewsJilaSlugDistrictSubDistrictSlugIndexRoute
  '/news/$jilaSlug/district/$subDistrictSlug/category/$categorySlug': typeof NewsJilaSlugDistrictSubDistrictSlugCategoryCategorySlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/users': typeof AdminUsersRoute
  '/article/$slug': typeof ArticleSlugRoute
  '/category/$slug': typeof CategorySlugRoute
  '/admin': typeof AdminIndexRoute
  '/news/$jilaSlug': typeof NewsJilaSlugIndexRoute
  '/news/$jilaSlug/category/$categorySlug': typeof NewsJilaSlugCategoryCategorySlugRoute
  '/news/$jilaSlug/district/$subDistrictSlug': typeof NewsJilaSlugDistrictSubDistrictSlugIndexRoute
  '/news/$jilaSlug/district/$subDistrictSlug/category/$categorySlug': typeof NewsJilaSlugDistrictSubDistrictSlugCategoryCategorySlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/users': typeof AdminUsersRoute
  '/article/$slug': typeof ArticleSlugRoute
  '/category/$slug': typeof CategorySlugRoute
  '/admin/': typeof AdminIndexRoute
  '/news/$jilaSlug/': typeof NewsJilaSlugIndexRoute
  '/news/$jilaSlug/category/$categorySlug': typeof NewsJilaSlugCategoryCategorySlugRoute
  '/news/$jilaSlug/district/$subDistrictSlug/': typeof NewsJilaSlugDistrictSubDistrictSlugIndexRoute
  '/news/$jilaSlug/district/$subDistrictSlug/category/$categorySlug': typeof NewsJilaSlugDistrictSubDistrictSlugCategoryCategorySlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin/login'
    | '/admin/users'
    | '/article/$slug'
    | '/category/$slug'
    | '/admin/'
    | '/news/$jilaSlug/'
    | '/news/$jilaSlug/category/$categorySlug'
    | '/news/$jilaSlug/district/$subDistrictSlug/'
    | '/news/$jilaSlug/district/$subDistrictSlug/category/$categorySlug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/login'
    | '/admin/users'
    | '/article/$slug'
    | '/category/$slug'
    | '/admin'
    | '/news/$jilaSlug'
    | '/news/$jilaSlug/category/$categorySlug'
    | '/news/$jilaSlug/district/$subDistrictSlug'
    | '/news/$jilaSlug/district/$subDistrictSlug/category/$categorySlug'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin/login'
    | '/admin/users'
    | '/article/$slug'
    | '/category/$slug'
    | '/admin/'
    | '/news/$jilaSlug/'
    | '/news/$jilaSlug/category/$categorySlug'
    | '/news/$jilaSlug/district/$subDistrictSlug/'
    | '/news/$jilaSlug/district/$subDistrictSlug/category/$categorySlug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ArticleSlugRoute: typeof ArticleSlugRoute
  CategorySlugRoute: typeof CategorySlugRoute
  NewsJilaSlugIndexRoute: typeof NewsJilaSlugIndexRoute
  NewsJilaSlugCategoryCategorySlugRoute: typeof NewsJilaSlugCategoryCategorySlugRoute
  NewsJilaSlugDistrictSubDistrictSlugIndexRoute: typeof NewsJilaSlugDistrictSubDistrictSlugIndexRoute
  NewsJilaSlugDistrictSubDistrictSlugCategoryCategorySlugRoute: typeof NewsJilaSlugDistrictSubDistrictSlugCategoryCategorySlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/category/$slug': {
      id: '/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof CategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/article/$slug': {
      id: '/article/$slug'
      path: '/article/$slug'
      fullPath: '/article/$slug'
      preLoaderRoute: typeof ArticleSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/news/$jilaSlug/': {
      id: '/news/$jilaSlug/'
      path: '/news/$jilaSlug'
      fullPath: '/news/$jilaSlug/'
      preLoaderRoute: typeof NewsJilaSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/$jilaSlug/category/$categorySlug': {
      id: '/news/$jilaSlug/category/$categorySlug'
      path: '/news/$jilaSlug/category/$categorySlug'
      fullPath: '/news/$jilaSlug/category/$categorySlug'
      preLoaderRoute: typeof NewsJilaSlugCategoryCategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/$jilaSlug/district/$subDistrictSlug/': {
      id: '/news/$jilaSlug/district/$subDistrictSlug/'
      path: '/news/$jilaSlug/district/$subDistrictSlug'
      fullPath: '/news/$jilaSlug/district/$subDistrictSlug/'
      preLoaderRoute: typeof NewsJilaSlugDistrictSubDistrictSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/$jilaSlug/district/$subDistrictSlug/category/$categorySlug': {
      id: '/news/$jilaSlug/district/$subDistrictSlug/category/$categorySlug'
      path: '/news/$jilaSlug/district/$subDistrictSlug/category/$categorySlug'
      fullPath: '/news/$jilaSlug/district/$subDistrictSlug/category/$categorySlug'
      preLoaderRoute: typeof NewsJilaSlugDistrictSubDistrictSlugCategoryCategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminLoginRoute: typeof AdminLoginRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminLoginRoute: AdminLoginRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ArticleSlugRoute: ArticleSlugRoute,
  CategorySlugRoute: CategorySlugRoute,
  NewsJilaSlugIndexRoute: NewsJilaSlugIndexRoute,
  NewsJilaSlugCategoryCategorySlugRoute: NewsJilaSlugCategoryCategorySlugRoute,
  NewsJilaSlugDistrictSubDistrictSlugIndexRoute:
    NewsJilaSlugDistrictSubDistrictSlugIndexRoute,
  NewsJilaSlugDistrictSubDistrictSlugCategoryCategorySlugRoute:
    NewsJilaSlugDistrictSubDistrictSlugCategoryCategorySlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
